export const tags = {
  ATTACK: "Attack",
  DEFENSE: "Defense",
  EXPERTISE: "Expertise",
  MELEE: "Melee",
  MODULAR: "Modular",
  MOVEMENT: "Movement",
  RANGED: "Ranged",
  RECOVERY: "Recovery",
  RESPONSE: "Response",
  SOCIAL: "Social",
  SPECIAL: "Special",
  STATS: "Stags",
  STEALTH: "Stealth",
  SURVIVAL: "Survival",
  UP_DEFENSE: "Up Defense",
  UP_ATTACK: "Up Attack",
  UTILITY: "Utility",
  VESSEL: "Vessel",
} as const;
