export const WikiArticleLinks= {
  WELCOME: "welcome",
    GETTING_STARTED: "getting-started",
    CHARACTER_CREATION: "character-creation",
    SKILLS: "skills",
    COMBAT: "combat",
    SPECIES: "species",
    GEAR: "gear",
    GEAR_SUIT: "gear-suit",
    GEAR_SUIT_ACCENT: "gear-suit-accent",
    GEAR_NON_SUIT: "gear-nonsuit",
    LEVELING: "leveling",
    LEVELING_FEATS: "leveling-feats",
    LEVELING_MODULAR_AUGMENTS: "leveling-modular-augments",
    LEVELING_MODULAR_COMPANION: "leveling-modular-companion",
    LEVELING_MODULAR_CYBERNETICS: "leveling-modular-cybernetics",
    LEVELING_MODULAR_PSIONICS: "leveling-modular-psionics",
    SPECIES_BEK: "species-bek",
    SPECIES_CHYRAX: "species-chyrax",
    SPECIES_DRKARI: "species-drakari", 
    SPECIES_DROIDS: "species-droids",
    SPECIES_EMPIANS: "species-empians",
    SPECIES_FEYRA: "species-feyra",
    SPECIES_FLONA: "species-flona",
    SPECIES_HUMANS: "species-humans",
    SPECIES_LOCANUS: "species-locanus",
    SPECIES_PAWNIANS: "species-pawnians",
    SPECIES_RHAZAK: "species-rhazak",
    SPECIES_URZI: "species-urzi",
    SPECIES_VELKI: "species-velki",
    SPECIES_VRANTS: "species-vrants",
    SPECIES_ZIVREN: "species-zivren",
} as const;

export type WikiArticleLinkEnum = typeof WikiArticleLinks[keyof typeof WikiArticleLinks];
